### ISSUE TITLE
Explain what this plugin do

### ISSUE THREAD

**Issue by vitonsky** [fpetrakov/stylelint-gamut#11]
Improve your docs - add to readme header short description what exactly this plugin do.

When people search tools on github, their look at repository description and head of readme to fast search and ignore unnecessary tools. Let's add something like "warn colors out of sRGB" to head of readme. If you will introduce new features, just extend your short description with no details explaining

**Comment by fpetrakov** [comment]
Thanks for the contribution!

I've reordered some sections in docs. Now the rules are at the top. I think, this way it's much easier to understand what the plugin does.
