### ISSUE TITLE
Migrate to culori and add checks for p3 and rec2020 color spaces

### ISSUE THREAD

**Issue by fpetrakov** [fpetrakov/stylelint-gamut#12]
Right now if a color goes out of sRGB gamut you should wrap it in `@media (color-gamut: p3)`. There is a problem because if color is out of sRGB gamut space, it doesn't mean it is in P3 space. It also can be in rec2020 space and wrapping it in `@media (color-gamut: p3)` is useless in this case. If color is in rec2020 color space we should wrap it in `@media (color-gamut: rec2020)` instead. 

[I have a draft code, but the problem with it is for some reason oklab colors always give only true or only false on checks.](https://gist.github.com/fpetrakov/1d492133b855165038667f0d1498fc89#file-colorspaceschecks-js)

Is it working properly and I just don't understand smth?

**Comment by fpetrakov** [comment]
@ai can you have a look at the code please if you have time?

**Comment by ai** [comment]
Can you create the same example with OKLCH? I am better with them.

**Comment by ai** [comment]
Rec2020 contains P3 and sRGB spaces.

You can use a snippet like:

```js
function getSpace (color) {
  if (inSrgb(color)) {
    return 'srgb'
  } else if (inP3(color)) {
    return 'p3'
  } else if (inRec2020(color)) {
    return 'rec2020'
  } else {
    return 'outside-all'
  }
}
```

**Comment by fpetrakov** [comment]
> Rec2020 contains P3 and sRGB spaces.

Oh, you are right, stupid mistake. For some reason I thought that if the color is in Rec2020 color space it means that it's always out of P3 and sRGB spaces. 

> You can use a snippet like:
> 
> ```js
> function getSpace (color) {
>   if (inSrgb(color)) {
>     return 'srgb'
>   } else if (inP3(color)) {
>     return 'p3'
>   } else if (inRec2020(color)) {
>     return 'rec2020'
>   } else {
>     return 'outside-all'
>   }
> }
> ```

Thanks!
