### ISSUE TITLE
More flexible check for media query

### ISSUE THREAD

**Issue by ai** [fpetrakov/stylelint-gamut#4]
```js
return parent.name === 'media' && parent.params === '(color-gamut: p3)'
```

This check is too strict. It doesn’t allow media query like:

```css
@media (prefers-color-scheme: dark) and (color-gamut: p3) { }
```

or even CSS after minification (no space before `p3`:

```css
@media (color-gamut:p3){}
```

I suggest changing check to:

```js
return parent.name === 'media' && /\(color-gamut:\s*p3\)/.test(parent.params)
```

**Comment by fpetrakov** [comment]
True, even more bugs will arise later. Thanks for suggestion, I will add some tests and change the check today.

**Comment by fpetrakov** [comment]
@ai The changes are made, thanks for contributing!
