### ISSUE TITLE
Add support for combined properties

### ISSUE THREAD

**Issue by ai** [fpetrakov/stylelint-gamut#6]
`border` or `background` may contain many values in additional to color:

```css
.foo {
  border: 4px solid oklch(100% 0 0);
}
```

Right now, plugin returns error:

```
Could not parse 4px solid oklch(100% 0 0) as a color. Missing a plugin?
```

I suggest finding color in declaration’s value. We can use RegExp or some PostCSS value parser:

```js
if (decl.value.includes('lch(') || decl.value.includes('lab(')) {
  let colors = decl.value.match(/(oklch|oklab|lab|lch)\([^\)]+\)/g)
  if (colors) {
    for (let color of colors) {
      checkColor(color)
    }
  }
}
```

Note, that some properties has multiple colors.

**Comment by fpetrakov** [comment]
Great suggestion, will add it asap.

**Comment by fpetrakov** [comment]
@ai I've added the changes, so you can update your package version to the latest one. Huge thanks for contributing!
